#FAS 1: CRIAR O BANCO DE DADOS (SCHEMA OU DATABASE):
#MEU PRIMEIRO BANQUINHO
CREATE SCHEMA ECI_CC1M;

#FASE 2: SELECIONAR O NOVO SCHEMA OU DATABASE PARA USO:
#USANDO MEU BANQUINHO
USE EC1_CC1M;

#FASE 3: CRIANDO AS TABELINHAS SEM CHAVES ESTRANGEIRAS
#CRIANDO A TABELINHA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(45) NOT NULL,
FORNEC_CEP VARCHAR(10) NOT NULL,
FORNEC_TEL VARCHAR(15) NOT NULL,
FORNEC_CONT TEXT NOT NULL
);

#CRIANDO A TABELINHA FILIAIS
CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(45) NOT NULL,
FILIAL_NUMRUA INT,
FILIAL_BAIRRO VARCHAR(45) NOT NULL,
FILIAL_CIDADE VARCHAR(45) NOT NULL,
FILIAL_ESTADO VARCHAR(45) NOT NULL,
FILIAL_PAIS VARCHAR(45) NOT NULL,
FILIAL_CEP VARCHAR(10) NOT NULL,
FILIAL_CAP TEXT NOT NULL
);

#CRIANDO A TABELINHA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESC TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIMED VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

#FASE 4: CRIAR AS TABELAS COM DEPENDÊNCIA DE CHAVE ESTRANGEIRA
#CRIANDO A TABELINHA PEDIDOS
CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_COD INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREV DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA') NOT NULL,
PED_FORNECEDORES INT NOT NULL, #NOSSA CHAVE ESTRANGEIRA DE FORNECEDOR
#CRIANDO A REFERENCIA PARA A CHAVE ESTRANGEIRA
#RESTRICAO - APELIDO - CH.ESTRANGEIRA(CAMPO CRIADO) REFERENCIA TABELA(CH.PRIMÁRIA)
CONSTRAINT FK_FORNECEDORES FOREIGN KEY (PED_FORNECEDORES) REFERENCES FORNECEDORES(FORNEC_COD)
);

#CRIANDO A TABELINHA RECEBIMENTOS
CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3) NOT NULL,
RECEB_COND TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY (RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_COD)
);

#FASE 5: CRIANDO AS TABELAS ASSOCIATIVAS (ENTIDADES ASSOCIATIVAS)
#CRIANDO A TABELINHA FILIAIS_PRODUTOS
CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAIS INT,
FLPR_PRODUTOS INT,
PRIMARY KEY (FILIAIS,PRODUTOS),
FLPR_PROD_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY (FLPR_FILIAIS) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY (FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#CRIANDO A TABELINHA FORNECEDORES_PRODUTOS
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FILIAIS INT,
FRPR_PRODUTOS INT,
PRIMARY KEY (FORNECEDORES,PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY (FRPR_FILIAIS) REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY (FRPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#CRIANDO A TABELINHA PEDIDOS_PRODUTOS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY (PEDIDOS,PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY (PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_COD),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY (PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);