CREATE SCHEMA EX1_FIX;

USE EX1_FIX;

CREATE TABLE IF NOT EXISTS PARTICIPANTES(
PART_NUM_INSC INT,
PART_CPF VARCHAR(20),
PART_NOME VARCHAR(100) NOT NULL,
PART_DATA_NASC DATE NOT NULL,
PART_EMPRESA VARCHAR(100),
PRIMARY KEY(PART_NUM_INSC, PART_CPF)
);

CREATE TABLE IF NOT EXISTS LOCAIS(
LOCAL_ID INT PRIMARY KEY,
LOCAL_NOME VARCHAR(100) NOT NULL,
LOCAL_LOG VARCHAR(100) NOT NULL,
LOCAL_NUMLOG INT,
LOCAL_BAIRRO VARCHAR(100) NOT NULL,
LOCAL_CIDADE VARCHAR(100) NOT NULL,
LOCAL_UF CHAR(2) NOT NULL,
LOCAL_CEP VARCHAR(20) NOT NULL,
LOCAL_CAPAC INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENTOS(
EVENTO_ID INT PRIMARY KEY,
EVENTO_NOME VARCHAR(100) NOT NULL,
EVENTO_DATA DATE NOT NULL,
EVENTO_ENTD VARCHAR(100) NOT NULL,
EVENTO_LOCAL INT,
CONSTRAINT FK_LOCAIS foreign key (EVENTO_LOCAL) references LOCAIS(LOCAL_ID)
);

CREATE TABLE IF NOT EXISTS ATIVIDADES(
ATIV_ID INT PRIMARY KEY,
ATIV_NOME VARCHAR(100) NOT NULL,
ATIV_DATA DATE NOT NULL,
ATIV_HORA TIME NOT NULL,
ATIV_EVNT INT NOT NULL,
CONSTRAINT FK_EVENTOS foreign key (ATIV_EVNT) references EVENTOS(EVENTO_ID)
);

CREATE TABLE IF NOT EXISTS PARTICIPANTE_EVENTO(
PAEV_NUM_INSC INT,
PAEV_CPF VARCHAR(20),
PAEV_EVENTO INT,
PRIMARY KEY (PARTICIPANTES,EVENTOS),
CONSTRAINT PAEV_FK_PARTICIPANTES FOREIGN KEY (PAEV_NUM_INSC) REFERENCES PARTICIPANTES(PART_NUM_INSC),
CONSTRAINT PAEV_FK_PARTICIPANTES FOREIGN KEY (PAEV_CPF) REFERENCES PARTICIPANTES(PART_CPF),
CONSTRAINT PAEV_FK_EVENTOS FOREIGN KEY (PAEV_EVENTO) REFERENCES EVENTOS(EVENTO_ID)
);

CREATE TABLE IF NOT EXISTS PARTICIPANTE_ATIVIDADE(
PAAT_NUM_INSC INT,
PAAT_CPF VARCHAR(20),
PAAT_ATV INT,
PRIMARY KEY (PARTICIPANTES,ATIVIDADES),
CONSTRAINT PAAT_FK_PARTICIPANTES FOREIGN KEY (PAAT_NUM_INSC) REFERENCES PARTICIPANTES(PART_NUM_INSC),
CONSTRAINT PAAT_FK_PARTICIPANTES FOREIGN KEY (PAAT_CPF) REFERENCES PARTICIPANTES(PART_CPF),
CONSTRAINT PAAT_FK_EVENTOS FOREIGN KEY (PAAT_ATV) REFERENCES ATIVIDADES(ATIV_ID)
);

