create schema ex02_fix1;

use ex02_fix1;

create table if not exists USUARIOS(
ID_USER INT PRIMARY KEY,
NOME_USER VARCHAR(100) NOT NULL,
SBRNOME_USER VARCHAR(100) NOT NULL,
EMAIL_USER VARCHAR(20) NOT NULL
);

create table if not exists GRUPOS(
ID_GRUPO INT PRIMARY KEY,
NOME_GRUPO VARCHAR(100) NOT NULL,
DESC_GRUPO TEXT NOT NULL
);

create table if not exists POSTAGENS(
ID_POST INT PRIMARY KEY,
TEXTO_POST TEXT,
IMG_POST BLOB,
DTHR_POST DATETIME NOT NULL,
USER_POST INT NOT NULL,
CONSTRAINT FK_USUARIOS FOREIGN KEY (USER_POST) REFERENCES USUARIOS(ID_USER)
);

create table if not exists COMENTARIOS(
ID_COMENT INT PRIMARY KEY,
TEXTO_COMENT TEXT NOT NULL,
DTHR_COMENT DATETIME NOT NULL,
USER_COMENT INT NOT NULL,
POST_COMENT INT NOT NULL,
CONSTRAINT FK_USUARIOS2 FOREIGN KEY (USER_COMENT) REFERENCES USUARIOS(ID_USER),
CONSTRAINT FK_POSTAGENS FOREIGN KEY (POST_COMENT) REFERENCES POSTAGENS(ID_POST)
);

create table if not exists USUARIOS_GRUPOS(
USGR_USUARIOS INT,
USGR_GRUPOS INT,
PRIMARY KEY (USGR_USUARIOS,USGR_GRUPOS),
CONSTRAINT FK_USUARIOS3 FOREIGN KEY (USGR_USUARIOS) REFERENCES USUARIOS(ID_USER),
CONSTRAINT FK_GRUPOS FOREIGN KEY (USGR_GRUPOS) REFERENCES GRUPOS(ID_GRUPO)
);

create table if not exists SEGUIDORES_USUARIOS(
SGUS_USUARIOS INT,
SGUS_SEGUIDOR INT,
PRIMARY KEY (SGUS_USUARIOS,SGUS_SEGUIDOR),
CONSTRAINT FK_USUARIOS4 FOREIGN KEY (SGUS_USUARIOS) REFERENCES USUARIOS(ID_USER),
CONSTRAINT FK_USUARIOS5 FOREIGN KEY (SGUS_SEGUIDOR) REFERENCES USUARIOS(ID_USER)
);