create schema ex3_fix;

use ex3_fix;

create table if not exists FILMES(
ID_FILME INT PRIMARY KEY,
NOME_FILME VARCHAR(100) NOT NULL,
DTRB_FILME VARCHAR(100) NOT NULL,
TEMPO_FILME INT NOT NULL,
DIRETOR_FILME VARCHAR(50) NOT NULL
);

create table if not exists SALAS(
ID_SALA INT PRIMARY KEY,
NOME_SALA VARCHAR(50) NOT NULL,
CAPAC_SALA INT NOT NULL
);

create table if not exists ESPECTADORES(
ID_ESPEC INT PRIMARY KEY,
TEL_ESPEC VARCHAR(20),
EMAIL_ESPEC VARCHAR(50) NOT NULL,
NOME_ESPEC VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL
);

create table if not exists SESSOES(
ID_SESSAO INT PRIMARY KEY,
FILME_SESSAO INT NOT NULL,
SALA_SESSAO INT NOT NULL,
CONSTRAINT FK_FILMES FOREIGN KEY (FILME_SESSAO) references FILMES(ID_FILME),
CONSTRAINT FK_SALAS FOREIGN KEY (SALA_SESSAO) references SALAS(ID_SALA)
);

create table if not exists INGRESSOS(
ID_INGRESSO INT PRIMARY KEY,
DATA_ING DATE NOT NULL,
HORA_ING TIME NOT NULL,
SESSAO_ING INT NOT NULL,
ESPEC_ING INT NOT NULL,
CONSTRAINT FK_SESSOES FOREIGN KEY (SESSAO_ING) REFERENCES SESSOES(ID_SESSAO),
CONSTRAINT FK_ESPECTADORES FOREIGN KEY (ESPEC_ING) REFERENCES ESPECTADORES(ID_ESPEC)
);

